//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApp1.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naciśnij ENTER, aby zakończyć działanie programu.
        /// </summary>
        internal static string Common_ExitApp {
            get {
                return ResourceManager.GetString("Common_ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby użyć tej funkcji, musisz mieć połączenie z internetem.
        /// </summary>
        internal static string Common_NoInternetConnection {
            get {
                return ResourceManager.GetString("Common_NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taka opcja jest niedostępna.
        /// </summary>
        internal static string Common_OptionIsNotAvailable {
            get {
                return ResourceManager.GetString("Common_OptionIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skąd chcesz wydobyć adresy email?.
        /// </summary>
        internal static string GetEmails_GetType {
            get {
                return ResourceManager.GetString("GetEmails_GetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Tekst.
        /// </summary>
        internal static string GetEmails_Text {
            get {
                return ResourceManager.GetString("GetEmails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Strona internetowa.
        /// </summary>
        internal static string GetEmails_Website {
            get {
                return ResourceManager.GetString("GetEmails_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst ,z którego chcesz wypisać adresy email.
        /// </summary>
        internal static string GetEmailsFromLocalString_GetString {
            get {
                return ResourceManager.GetString("GetEmailsFromLocalString_GetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz adres strony:.
        /// </summary>
        internal static string GetEmailsFromWebsite_EnterUrl {
            get {
                return ResourceManager.GetString("GetEmailsFromWebsite_EnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona pod adresem {0} nie została odnaleziona.
        /// </summary>
        internal static string GetEmailsFromWebsite_SiteIsUnavailable {
            get {
                return ResourceManager.GetString("GetEmailsFromWebsite_SiteIsUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres {0} nie jest poprawnym adresem.
        /// </summary>
        internal static string GetEmailsFromWebsite_UrlIsInvalid {
            get {
                return ResourceManager.GetString("GetEmailsFromWebsite_UrlIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz funkcję:.
        /// </summary>
        internal static string Main_ChooseFunction {
            get {
                return ResourceManager.GetString("Main_ChooseFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Wypisz listę adresów email.
        /// </summary>
        internal static string Main_GetEmailAddresses {
            get {
                return ResourceManager.GetString("Main_GetEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Wyjdź.
        /// </summary>
        internal static string Main_Quit {
            get {
                return ResourceManager.GetString("Main_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Walidacja kodu pocztowego.
        /// </summary>
        internal static string Main_ValidateZipCode {
            get {
                return ResourceManager.GetString("Main_ValidateZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono żadnych adresów email.
        /// </summary>
        internal static string PrintList_DidntFoundAnyEmails {
            get {
                return ResourceManager.GetString("PrintList_DidntFoundAnyEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Należy on do.
        /// </summary>
        internal static string ValidateZipCode_BelongsTo {
            get {
                return ResourceManager.GetString("ValidateZipCode_BelongsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany kod jest.
        /// </summary>
        internal static string ValidateZipCode_CodeValidation {
            get {
                return ResourceManager.GetString("ValidateZipCode_CodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz kod pocztowy:.
        /// </summary>
        internal static string ValidateZipCode_EnterZipCode {
            get {
                return ResourceManager.GetString("ValidateZipCode_EnterZipCode", resourceCulture);
            }
        }
    }
}
